### ISSUE TITLE
Request user documentation

### ISSUE THREAD

**Issue by WizzerWorks** [tulios/json-viewer#10]
It is not clear to me how to use this extension. Do you have instructions on how to load a JSON file? I typed in "json-viewer <tab>" in the text field for the Chrome browser. What do I type in next? What are the commands?

I would like to view a file on my file system. Do you have an example on how to do this?

**Comment by olsen4930824** [comment]
Thanks, but it'd be really helpful for others if you add this in the README.md

**Comment by horizon365** [comment]
Not work on local json data. Chrome 84.0.4147.105

![TIM截图20200923153247](https://user-images.githubusercontent.com/17285011/93981116-19f95c80-fdb2-11ea-8ecc-45f85975c50e.png)
