### ISSUE TITLE
Always show fold/unfold button

### ISSUE THREAD

**Issue by KIVagant** [tulios/json-viewer#107]
Hello.

I have a big json response that I want to fold. But in all another cases I prefer to see full response without folding. Unfortunately, the "fold/unfold" button appears only if "alwaysFold" option is true.

Please, make the button always visible by default or optionally with related config.

Thank you, this is my favorite browser extension.

**Comment by tulios** [comment]
I have this problem myself, it's a good idea.

**Comment by tulios** [comment]
Released on version 0.16.0
