### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by matanster** [tulios/json-viewer#11]
Works as advertized :) 
Can it also use the font shown on the settings page themes (I think it's called comic or something) rather than Chrome's default font? a thicker font is easier for 'glossing-and-fishing' which is what we typically do with json (we don't read json). (I'm a bit reluctant changing my default font in Chrome itself as I can't tell what that will also affect)

**Comment by tulios** [comment]
Version 0.8.0 now is completely customizable
