### ISSUE TITLE
Add Panda Syntax to themes

### ISSUE THREAD

**Issue by siamak** [tulios/json-viewer#112]
Hi. Please add Panda Syntax theme to JSON viewer themes. I was added this theme to Codemirror. [panda-syntax 'codemirror'](https://github.com/codemirror/CodeMirror/blob/master/theme/panda-syntax.css).

**Comment by tulios** [comment]
Sure, it looks super cool.

**Comment by tulios** [comment]
Released on version 0.16.0

**Comment by siamak** [comment]
Thanks @tulios ;)
