### ISSUE TITLE
只能针对JSON格式的数据进行转化，不能对JSON字符串进行格式化

### ISSUE THREAD

**Issue by Michaelyb520** [tulios/json-viewer#120]
您好，发现一个很大问题，不能对json字符串进行转化，只能转换json格式的数据。
例如：下面链接就不行。
http://hq.kuaiex.com/Price/hs_TopN?des=0&size=30

这个链接可以：
https://www.btc123.com/kline/klineapi?type=1min&symbol=huobibtccny&size=300

**Comment by tulios** [comment]
Hi, the first API is returning `text/html` as its content type. PR #117 should fix it soon

Thanks

**Comment by tulios** [comment]
This was fixed on version 0.16.0.
