### ISSUE TITLE
Empty <pre> prepended to body

### ISSUE THREAD

**Issue by theNailz** [tulios/json-viewer#123]
JSON-viewer is prepending an empty `<pre>`-tag to my body of certain websites since today.
JSON-viewer: 0.16.0
Chrome: 54.0.2840.99 m

http://i.imgur.com/SUJ7C47.png

http://i.imgur.com/SoLmRU9.png

**Comment by tulios** [comment]
Oh, this is bad. I'll take a look at it asap.
Thanks!

**Comment by boghyon** [comment]
I'm having the same problem. But strangely only my private project (web app) on a localhost.
Chrome: 54.0.2840.99 m

**Comment by theNailz** [comment]
Nope @tulios, local development project. Same as @boghyon, only on local dev, not on a public site.

**Comment by tulios** [comment]
@boghyon @theNailz I have an ideia of what is causing this, I'll provide a fix today.
Thanks again.

**Comment by lucaskalves** [comment]
Same problem here. It is not happening on a local project. It's happening in our remote servers.

**Comment by tulios** [comment]
I'm looking at this now

**Comment by tulios** [comment]
@lucaskalves can you provide the html for testing? you can mask the content if needed.

**Comment by tulios** [comment]
Hey guys, my hint was false and I'm having a bad time trying to reproduce this. Can one of you provide a html (mask the data if you need) that causes the problem?

I tried on everything I use (apis and sites) and I can't reproduce it.

**Comment by boghyon** [comment]
Sorry for late response. Here is a hello world example using OpenUI5 framework. [OpenUI5 - hello_world.zip](https://github.com/tulios/json-viewer/files/627978/OpenUI5.-.hello_world.zip)
Prerequisite: [https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb](url)
Start the extension, set the folder to the path where index.html is, and start the web server to bypass SOP.
Ignore errors like "missing Component-preload" and i18n related stuff.

**Comment by tulios** [comment]
Hey guys, thank you very much for the help with this bug.

The bugfix was released on version `0.16.1`.

Thanks again!

**Comment by lucaskalves** [comment]
Great to see you managed to fix it. I can't provide the html of the solution because of confidentiability matters, but I am also using something related to Open UI5.

Thanks a lot, @tulios
