### ISSUE TITLE
Conflict with zoomWheel extension

### ISSUE THREAD

**Issue by kenime** [tulios/json-viewer#127]
my JSON viewer was not working and I digged into the code. Turns on another extension "[zoomWheel](https://chrome.google.com/webstore/detail/zoomwheel/kdfgigbjonaniokmpfflpflkhahhbaej?hl=en)" creates 2 elements under `document.body.childNodes`, so when JSON viewer is executing `getPreWithSource()`, the following checking will fail and not considering the page as JSON.

```
var childNodes = document.body.childNodes;

  if (childNodes.length === 1) {
```

Would there be any impact if we loosen the checking as `childNodes.length > 0` ?

**Comment by benvan** [comment]
See https://github.com/tulios/json-viewer/pull/133

**Comment by tulios** [comment]
Version 0.16.2 is out! Thanks @benvan for the PR :)
