### ISSUE TITLE
New Feature: Area to paste JSON

### ISSUE THREAD

**Issue by kingjerod** [tulios/json-viewer#13]
I find myself having to copy/paste JSON from places and it would be nice to have a section in the extension for doing this. You can do it currently by typing json-viewer + tab in the Omnibox, then pasting what you want and hitting enter, but having to type json-viewer every time is slow. There is also no way to make a nice bookmark out of it. Just a page in the extension that could be bookmarked, that simply has a big text area and a button that says "Format" would be nice.

**Comment by tulios** [comment]
I am working on a scratch pad area, soon we will have this feature.
