### ISSUE TITLE
riot js does not work at version 0.16.2

### ISSUE THREAD

**Issue by 1984weed** [tulios/json-viewer#136]
Hi

I love this project.
But I found that riot js does not work, because of this extension.

For example

You open this page http://riotjs.com/made-with-riot/ and click some links with chrome enabled json-viewer 0.16.2

Then js error happen, like this 

![screen shot 2017-01-16 at 13 11 20](https://cloud.githubusercontent.com/assets/2726968/21970771/4f0b85a0-dbed-11e6-8370-8f3c43a9aedd.png)

If you disabled json viewer, it won't happen.

Thanks.

**Comment by sirxemic** [comment]
I got a similar issue for a Vue project. Commit 3b61cfe seems to have introduced this bug.

**Comment by tulios** [comment]
Sorry guys, this is bad. I have an idea on how to solve this, I'll take a look now. Thanks for the report

**Comment by tulios** [comment]
@1984weed @sirxemic 05f7c32 should fix it, I going to release 0.16.3 with the fix

**Comment by tulios** [comment]
0.17.0 is out with the fix, can you ping this issue back when you test it? (it usually takes 1h for chrome store to expose the new version). Thanks again!

**Comment by tulios** [comment]
0.17.0 is already available

**Comment by 1984weed** [comment]
@tulios 
I installed and checked at 0.17.0.
It looks good for riot js 👍 

Thanks.

**Comment by tulios** [comment]
Thanks @1984weed
