### ISSUE TITLE
Array Length not displaying.

### ISSUE THREAD

**Issue by KINGH242** [tulios/json-viewer#143]
The count of items is not displaying.  I have the latest version that includes the changes that is supposed to add this feature but it is not displaying the count or the option.  I added the option manually and it still doesn't work.  I can, however, get the length in the console by doing

`window.json.length`

**Comment by tulios** [comment]
Hi, json-viewer doesn't have this feature yet. There is a PR (#122) adding this feature but it's not merged.

**Comment by tulios** [comment]
This feature is out in version 0.18.0

Thanks
