### ISSUE TITLE
Encoding request: Force utf-8

### ISSUE THREAD

**Issue by boghyon** [tulios/json-viewer#146]
Some requested json files don't append `charset=utf-8` in the content-type of response headers which leads to unreadable strings. **Example:** https://openui5.hana.ondemand.com/resources/sap/ui/core/cldr/ko.json
> Content-Type: application/json

Is there any workarounds to enforce it to display the content in utf-8? It would be nice if this extension could support it out of the box without having to install any other extension.

**Comment by tulios** [comment]
👍  I like the idea

**Comment by ak04nv** [comment]
Very actual after this [news](https://productforums.google.com/forum/#!topic/chrome/2JIo6Yu7K-I;context-place=forum/chrome) and this old forgotten [bug](https://bugs.chromium.org/p/chromium/issues/detail?id=438464)

**Comment by boghyon** [comment]
The current Canary version of Chrome displays [JSON in utf-8](https://chromium-review.googlesource.com/c/chromium/src/+/587829). I guess this issue is not relevant anymore if this extension is to be used for Chrome only.
