### ISSUE TITLE
Spaces lost in plain string

### ISSUE THREAD

**Issue by alexbowers** [tulios/json-viewer#152]
IF i am outputting json such as 

```php
json_encode("This is a string");
```

The output looks like:

![image](https://cloud.githubusercontent.com/assets/842974/25811927/a79edaba-340c-11e7-99a8-6d67d8987a00.png)

Where the raw output is:

```
"This is a string"
```

**Comment by alexbowers** [comment]
bump

**Comment by adius** [comment]
This is really annoying =(
