### ISSUE TITLE
Replace options with raw link/(un)collapse all

### ISSUE THREAD

**Issue by ahluntang** [tulios/json-viewer#16]
Right now, when viewing json files, in the right top corner there's a gear icon that links to the options. I can find those options through the extensions page as well (and honestly, I only configure those once, upon first usage), what would be more handy to see at every json file are more context-oriented links, like a link to a raw version of the json (not mangled by the extension) a link to collapse or uncollapse all nodes on the current json file etc.

**Comment by tulios** [comment]
In version 0.8.0 when you enable "alwaysFold" it will include a button to unfold everything
