### ISSUE TITLE
Great, but Require number of nodes to show

### ISSUE THREAD

**Issue by mohan-agadkar** [tulios/json-viewer#161]
It is by far the best json extension I found, after going through the other ones.
However one important option is missing.
Showing of the number of elements inside a node.

**Comment by tulios** [comment]
Hi, this was recently added. It should be available in the next release (`showArraySize`).

<img width="521" alt="screen shot 2017-10-23 at 18 15 36" src="https://user-images.githubusercontent.com/33231/31900311-4247df54-b81e-11e7-86f8-61a357a273d5.png">

<img width="493" alt="screen shot 2017-10-23 at 18 15 45" src="https://user-images.githubusercontent.com/33231/31900319-4aa02b5c-b81e-11e7-8022-044a94a9c507.png">
