### ISSUE TITLE
Doesn't trigger on Opera when installed through compatibility layer - possible fixes?

### ISSUE THREAD

**Issue by xZero707** [tulios/json-viewer#163]
I have recently switched to Opera after being faithful to Chrome ever since first release, and only thing I truly miss on Opera, is this extension. Opera outperformed Chrome in everything, at least in my case.

There is[ Chrome extensions compatibility layer add-on for Opera](https://addons.opera.com/en-gb/extensions/details/download-chrome-extension-9/), which allow installation of Chrome extensions on Opera, as name suggests. However although JSON Viewer installs just fine on Opera, and options page works perfectly, it doesn't trigger on JSON pages. 

Please note that this is only a question, not request, I don't demand you guys to import it to Opera. You've done fantastic work already.

**Comment by tulios** [comment]
Nice, I can take a look at opera's extension API. If it's similar we can make it work.

**Comment by xZero707** [comment]
I would like to help, but I'm back-end developer and front-end is not strong side of mine, especially not the extensions design. 
I will look and see if I can do anything, though.

**Comment by xZero707** [comment]
UPDATE: I just noticed that suddenly, it works. I'm not sure if it's an update on your side, or maybe compatibility layer plug-in update, but it works wonderfully, all of sudden.

**Comment by tulios** [comment]
🎉
