### ISSUE TITLE
Can't format floating point

### ISSUE THREAD

**Issue by bastaware** [tulios/json-viewer#167]
Doesn't format the json below. I guess it's because of the floating point decimals.

`[{"time":1.5034464E+9,"price":4118.566,"volume":0},{"time":1503526085.756,"price":4118.566,"volume":5625},{"time":1503526385.556,"price":4128.998,"volume":5624}]`

**Comment by tulios** [comment]
Related to #111

**Comment by tulios** [comment]
<img width="389" alt="screen shot 2017-10-23 at 18 09 19" src="https://user-images.githubusercontent.com/33231/31900002-6c279c5c-b81d-11e7-8e5b-01a94d8075d7.png">
