### ISSUE TITLE
Doesn't work on JSON endpoints with sandbox CSP

### ISSUE THREAD

**Issue by ngyikp** [tulios/json-viewer#178]
**Reproduction URLs:**
* https://raw.githubusercontent.com/tulios/json-viewer/master/package.json
* or https://untitled-8bobienkqieg.runkit.sh (source code: https://runkit.com/ngyikp/59f56f94648a720012dc14d3)

Both of these URLs have a response header of `Content-Security-Policy: sandbox`

**Tested on user-agents:**
* Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3252.0 Safari/537.36

**Expected result:**
The JSON viewer should work.

**Actual result:**
Doesn't work at all, page is completely blank, and a console error appears:
`Blocked script execution in 'https://untitled-8bobienkqieg.runkit.sh/' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

It's a misleading error, the extension's content script does run but halts at one point. I did some investigation and it might be a Chrome bug, `setTimeout` and `setInterval` doesn't work in the sandbox CSP, but `requestAnimationFrame` or `requestIdleCallback` works.

[I tried this patch and it works](https://github.com/ngyikp/json-viewer/commit/6b5fa84b6bebe9275ac3fa949a4e8a0e9876a565), there's still some buggy behaviour but at least it's not a white screen anymore.

~~Another thing with `requestAnimationFrame` is that [only Chrome 24+ has the unprefixed version](https://caniuse.com/#feat=requestanimationframe) and [the manifest's minimum Chrome version is 21](https://github.com/tulios/json-viewer/blob/2e7088aa0a0fc623033a4db99ffe6a329a4db44d/extension/manifest.json#L8), but I think no one should be using an ancient Chrome anymore :)~~ (replaced with https://github.com/tulios/json-viewer/issues/210)

**Comment by psyrendust** [comment]
I'm getting the same issue.

**Comment by VladimirAlexiev** [comment]
https://github.com/tulios/json-viewer/pull/209. If @tulios doesn't merge it soon, I'm switching too.

**Comment by ngyikp** [comment]
The Chrome bug has been reported by someone else, and fixed in Chrome 68 :)
https://bugs.chromium.org/p/chromium/issues/detail?id=811528

![](https://user-images.githubusercontent.com/6135313/43042228-c0c28cfa-8daa-11e8-945a-40df229b48f1.png)
