### ISSUE TITLE
Polluting simple web page

### ISSUE THREAD

**Issue by Asken** [tulios/json-viewer#180]
When have the extension enabled it pollutes a web page looking like this:

```
<!DOCTYPE html>
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        Text
    </body>
</html>
```

to this:

```
<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <pre>
           Text
	</pre>
    </body>
</html>
```

**Comment by amakhrov** [comment]
Similar for me.
Input (served with `Content-Type: text/html` header):
```
<html>
  <body>
    test
  </body>
</html>
```

result after json viewer formatting:
```
<html>
  <head>
    <style></style>
  </head>
  <body>
    <pre>
      test
    </pre>
  </body>
</html>
```

**Comment by tulios** [comment]
This is a very hard bug to fix, to properly fix this the extension should ignore anything that is `text/html` but some weird APIs insist in return the wrong mime-type, I think I will add a config to disable this behavior.

**Comment by c24w** [comment]
Just came across this today completely messing up this simple page:

![image](https://user-images.githubusercontent.com/710406/40927477-b8f3babc-6816-11e8-97ec-6f970b5f8bfb.png)

---

> some weird APIs insist in return the wrong mime-type

I don't know what those weird APIs are, but should this really be accommodating for the exceptions?  Any news on the config option? :slightly_smiling_face:
