### ISSUE TITLE
Enable for offline use?

### ISSUE THREAD

**Issue by ryanpcmcquen** [tulios/json-viewer#188]
Is there a reason not to enable this for offline use?

**Comment by tulios** [comment]
Hi @ryanpcmcquen, this extension already works offline. You have to allow it through the extensions page.

![screen shot 2018-02-05 at 09 26 48](https://user-images.githubusercontent.com/33231/35794623-c0ad883c-0a56-11e8-9dd2-078fabae39fc.png)

Just check "Allow access to file URLs"

**Comment by ryanpcmcquen** [comment]
I figured it did. We may as well update the manifest to reflect that.
