### ISSUE TITLE
It is not working on local json files.

### ISSUE THREAD

**Issue by halitogunc** [tulios/json-viewer#191]
It would be great if i can use json-viewer for my own local json files also.

**Comment by tulios** [comment]
Hi, take a look at issue #10 for instructions. It works with local files.

**Comment by fwd079** [comment]
Guess this is stopped again. I have this 👇 but still local JSONs are just plain text.

![image](https://user-images.githubusercontent.com/7912632/86962090-35ad7900-c15a-11ea-8254-d9a0011aec12.png)

Regards.
