### ISSUE TITLE
URL non clickable when there is no TLD in the domain name.

### ISSUE THREAD

**Issue by kyro38** [tulios/json-viewer#23]
I working on a local network so we don't use TLD in the domain name for our servers. Therefore the url in our JSON do not contain a TLD. 

It seems to be that you rely on that to make text clicable or not. 

Imho this should be fixed :)

**Comment by jamesrom** [comment]
:+1: 

Maybe it should use @dperini's [regex-weburl gist](https://gist.github.com/dperini/729294).

See also: [In search of the perfect URL validation regex](https://mathiasbynens.be/demo/url-regex)

**Comment by dperini** [comment]
The gist has been updated:  https://gist.github.com/dperini/729294

**Comment by tulios** [comment]
Thanks @dperini, regex updated.
