### ISSUE TITLE
UTF-8 Characters

### ISSUE THREAD

**Issue by ygbr** [tulios/json-viewer#24]
Hi,

Congrats for this awesome extension.

One problem I have detected is that UTF-8 accentuation is not rendered normally and instead it is escaped as \uXXXX

ex:
```json
{
  "s": [
    {
      "r": {},
      "q": "Quando voc\u00ea vai \u00e0 praia, costuma levar comes e bebes?",
      "t": "select",
      "fb": [],
      "fdata": {}
}]
}
```

I'm sending the correct encoding on response headers:
Content-Encoding:gzip
Content-Length:54119
Content-Type:application/json; charset=utf-8

Any hints?

![screen shot 2014-08-13 at 10 56 12 am](https://cloud.githubusercontent.com/assets/133589/3906284/a0f0678a-22f1-11e4-88c8-e0fed54c7a4e.png)

**Comment by KIVagant** [comment]
+1

**Comment by tulios** [comment]
I managed to fix this problem. I'll release another version this week.
