### ISSUE TITLE
It could have an input feature of json and display in a new tab the input value

### ISSUE THREAD

**Issue by henriqueweiand** [tulios/json-viewer#243]
It could have a feature of inputting json and visualizing in a new tab the value entered in this way would be useful for those who are implementing and want to see the values in a better way. I trust that I use some websites for this function.

**Comment by tulios** [comment]
This already exists, it's the scratch pad. Go to the address bar, type json-viewer scratch then <tab> paste the text and hit enter, it will open a new tab where you can change and reformat any value

**Comment by henriqueweiand** [comment]
nice!
