### ISSUE TITLE
Show render time / download time / latency on header

### ISSUE THREAD

**Issue by ygbr** [tulios/json-viewer#25]
Hi,

I have noticed that for large JSON files it takes a bit for rendering the JSON visualization.

It would be nice to show in the headers the actual time it took to download the JSON so we don't suspect of server issues.

Ex:

On a 53.1Kb JSON File, it took 1.15 sec for the download to take place of this particular JSON but the plugin kept spinning for about 6 seconds... It would be nice to know the actual time the server took to process it so I don't freak out about performance issues...

![screen shot 2014-08-13 at 11 01 43 am](https://cloud.githubusercontent.com/assets/133589/3906393/8c0f8a20-22f2-11e4-847b-69779c7093ac.png)

**Comment by tulios** [comment]
Version [0.8.0](https://github.com/tulios/json-viewer/tree/0.8.0) is out, it is a lot faster than the previous one. I will close this issue but if you try and it's not good enough I can reopen it.
