### ISSUE TITLE
The extension was disabled in Chrome version: 85.0.4183.83

### ISSUE THREAD

**Issue by cesarnorena** [tulios/json-viewer#259]
<img width="1904" alt="Screen Shot 2020-09-02 at 2 21 55 PM" src="https://user-images.githubusercontent.com/6949977/92015770-aa023400-ed27-11ea-8af3-5897cee28d1b.png">

**Comment by tulios** [comment]
Hi, you have manually disabled the extension before. You can click on "Ativar este item" to enable it again. I have the same version of chrome and the extension is working fine.
