### ISSUE TITLE
Not working for my staging server

### ISSUE THREAD

**Issue by gsklee** [tulios/json-viewer#29]
The extension is awesome, it works for http://graph.facebook.com/github and other public APIs the like, but when I'm view JSON response from my non-public devbox it's not working at all. Does it rely on something like HTTP headers to get things right?

**Comment by tulios** [comment]
Hi @gsklee it actually analyses the content to determine if it is a valid JSON or not, could you provide an example of your API output?

**Comment by gsklee** [comment]
@tulios Something as simple as this doesn't work:

```
{"ts": 1423448455.899794}
```

**Comment by tulios** [comment]
Try version [0.8.0](https://github.com/tulios/json-viewer/tree/0.8.0), a lot of bugs were fixed.
