### ISSUE TITLE
Extension not working for large json file

### ISSUE THREAD

**Issue by Cyberuben** [tulios/json-viewer#30]
Hi,

I have a large .json file (641KB) and I noticed that this application will not load it, under any circumstances. I really need to have a visual layout of this massive file and I thought your extension would be the best. I wouldn't mind sending you the file somewhere in private, but as it has information not meant to be completely public, I can't just post it here.

The file comes from a JSON.stringify() call in NodeJS and is valid according to http://www.freeformatter.com/json-validator.html and http://jsonlint.com/.

**Comment by tulios** [comment]
Hi, did you increased the kbyte size which the plugin uses to know if it should parse the json? Take a look at issue #27 if you don't know how to change this value.

**Comment by tulios** [comment]
The default value is 200kb

**Comment by Cyberuben** [comment]
My bad, I didn't look at that issue as the title was very vague, so I wouldn't have guessed it belonged to my issue. I solved it now, my apologies!

**Comment by tulios** [comment]
No problem. Thanks for report, this will help other users.
