### ISSUE TITLE
Preview / Raw buttons

### ISSUE THREAD

**Issue by KIVagant** [tulios/json-viewer#33]
Please, add two buttons beside settings button:

[ Preview ] [ Raw ]

First is enabled by default and show current view. Second will show original source.

**Comment by tulios** [comment]
I'm planning to include a button to the original source

**Comment by tulios** [comment]
I have included a button to toggle highlighted/raw version. Update to version [0.8.0](https://github.com/tulios/json-viewer/tree/0.8.0). Thanks.

**Comment by KIVagant** [comment]
Thank you!
