### ISSUE TITLE
Not showing in Microsoft Edge since they added their own JSON viewer

### ISSUE THREAD

**Issue by alexb148** [tulios/json-viewer#339]
The latest versions of Microsoft Edge (for Mac at least) seem to have implemented their own built in JSON viewer.

As a result this seems to have stopped this extension from working, which is annoying because this extension is vastly better.

Can't see a way to disable the Edge version, and I'm not sure if this is something you're able to resolve in the plugin itself or not, but I'd love to get this extension working again in my browser!

**Comment by wang-ran** [comment]
<img width="1300" alt="image" src="https://github.com/tulios/json-viewer/assets/12745859/72eb0262-d2d4-491f-9e61-29df5aa70c45">

disable "JSON Viewer"
It will work

**Comment by alexb148** [comment]
Thanks, I'd searched the Edge settings but not the feature flags - can confirm this flag setting works and solves the issue for me!

**Comment by MarvinXu** [comment]
Can't find this flag
![image](https://github.com/tulios/json-viewer/assets/7382357/8ee1e758-74b1-466c-94c6-eb48f6ae3ed7)

**Comment by stick-i** [comment]
This issue has reoccurred and we are unable to find the JSON viewer in the edge now!

**Comment by alexb148** [comment]
> This issue has reoccurred and we are unable to find the JSON viewer in the edge now!

Same here

**Comment by eswaryaga-tomtom** [comment]
same here I hate this default setting 
very slow renderer for huge json files

**Comment by Jarpiino** [comment]
found a fix, switched back to chrome

**Comment by oguzhaneren** [comment]
following workaround solution can help

https://superuser.com/questions/271678/how-do-i-pass-command-line-arguments-to-dock-items
`
open "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" --args--restart --flag-switches-begin --enable-webgl-draft-extensions --ignore-gpu-blocklist --flag-switches-end --disable-features=msEdgeJSONViewer
`
