### ISSUE TITLE
Show escaped strings as unescaped

### ISSUE THREAD

**Issue by KIVagant** [tulios/json-viewer#34]
Original json encoded source:

```
{"href":"\/some\/path\/here"} 
```

In extension this string looks escaped too, so I can't copy or click it. Please, show it as decoded.

**Comment by tulios** [comment]
I will have to think about this problem. I will probably have to decode some strings. Thanks.

**Comment by tulios** [comment]
I managed to fix this problem. I'll release another version this week.
