### ISSUE TITLE
Little improvement: sort themes in selector by darkness

### ISSUE THREAD

**Issue by KIVagant** [tulios/json-viewer#35]
Please, divide themes by they backgrounds: dark or light. I never use bright code themes, some people never use a dark one.

**Comment by tulios** [comment]
![darkness-group](https://cloud.githubusercontent.com/assets/33231/8365551/2f788954-1b64-11e5-95d2-8673b68b7365.png)

great suggestion, thanks! (included in 0.9.0, rolling out)

**Comment by KIVagant** [comment]
Thank you.
