### ISSUE TITLE
Failed to load CSS

### ISSUE THREAD

**Issue by Wideshanks** [tulios/json-viewer#39]
The stylesheet doesn't load anymore. Any ideas?

![image](https://cloud.githubusercontent.com/assets/2061925/8281111/ba4c461a-18b2-11e5-8286-3d4521774ed4.png)

**Comment by tulios** [comment]
Hi @Wideshanks, I will look this today. Could you try to disable/enable the extension again e see if it works (temporarily)? My chrome version is Version 43.0.2357.124 (64-bit), what is yours?

**Comment by tulios** [comment]
I just notice that the response is an error, I will check this. I believe that it is failing on error responses, I will try to fix it asap.

**Comment by tulios** [comment]
Errors have anything to do with this bug. I'll keep checking.

**Comment by Wideshanks** [comment]
I see the new 0.9.0, with the change to `MAX_WAIT`, but I still have the same behavior.

So I start with a new Chrome profile, only json-viewer 0.9.0 is installed:

![image](https://cloud.githubusercontent.com/assets/2061925/8378041/4c6ed326-1be4-11e5-9948-c91d17d24a59.png)

Chrome version:

![image](https://cloud.githubusercontent.com/assets/2061925/8377950/c1dc0dc8-1be3-11e5-839b-99957ae5490e.png)

I have the same error as before, but it now takes around 10 seconds for the JSON output to load, still without CSS.

![image](https://cloud.githubusercontent.com/assets/2061925/8377905/647f5b3a-1be3-11e5-85a6-7d4d45d3d6e7.png)

(The example used this time is a successful response, unlike the Facebook github endpoint above.)

The timeline in the image isn't easy to follow, but it's pausing for around 10 seconds and then paints the response on the screen

Network tab shows the document request itself finishing in 500ms.

![image](https://cloud.githubusercontent.com/assets/2061925/8378184/8b5cbcdc-1be5-11e5-9de4-da5347c772cf.png)

You can see I also get a `200` response on `viewer.css`. The URL of the CSS mentioned in the error message in the console is valid and I can access it:

![image](https://cloud.githubusercontent.com/assets/2061925/8377930/af7e1d7e-1be3-11e5-9d0b-6975f9e5504b.png)

The CSS data is valid and passes csslint.

The stack trace points to this line in [`load-css.js`](https://github.com/tulios/json-viewer/blob/master/extension/src/json-viewer/load-css.js#L29), in the `if (attempts > MAX_WAIT)`:

![image](https://cloud.githubusercontent.com/assets/2061925/8378085/ae3c1d34-1be4-11e5-8d0f-72b1900bf23c.png)

It looks like the `content` var here being compared to `loaded` or `'loaded'`:

![image](https://cloud.githubusercontent.com/assets/2061925/8378735/6fd9845a-1be9-11e5-96e5-303dc8e65ee0.png)

--ends up being an empty string:

![image](https://cloud.githubusercontent.com/assets/2061925/8378708/39f9714c-1be9-11e5-82ca-6d618e2daf92.png)

**Comment by tulios** [comment]
Hi @Wideshanks thanks for this great analysis, I will reopen the issue and try to reproduce this bug again

**Comment by tulios** [comment]
Hey @Wideshanks I finally found the problem, I will release 0.9.1 version. Thanks for your support and patience.

**Comment by Wideshanks** [comment]
**Well, you replied before I could send this, but here you go anyway**:

Spoke too soon. The version above was paused in the debugger on the first loop. The `content` is empty only for the first attempt (probably the reason you had a loop there to begin with).

If I directly modify the source of the extension to log `content`:

![image](https://cloud.githubusercontent.com/assets/2061925/8379016/289b13b8-1beb-11e5-8048-e18399a95fbe.png)

It's empty only on the first try, subsequent checks have it as `"loaded"`

![image](https://cloud.githubusercontent.com/assets/2061925/8378959/d1edb638-1bea-11e5-9e9f-96794e1a4b91.png)

So, the check is for single-quotes `'loaded'`, but my `content` var is showing double-quotes `"loaded"`. If I change that check, the CSS loads:

![image](https://cloud.githubusercontent.com/assets/2061925/8379125/df5d1bc8-1beb-11e5-9d32-046ab3d6a158.png)

Also, I would avoid comparing the number of `attempts` with a number of milliseconds in `MAX_WAIT` because the intended 2 second `MAX_WAIT` may not be 2 seconds, it'll be 2,000 attempts.

![image](https://cloud.githubusercontent.com/assets/2061925/8379133/f3f825be-1beb-11e5-9653-156e180706f9.png)

I see that each of the attempts has a `setTimeout` interval of 1ms, but on my machine at least, it takes way longer than 1ms.

**Comment by tulios** [comment]
![picture](https://cloud.githubusercontent.com/assets/33231/8379451/a34eef5c-1bf6-11e5-910c-4b3da11b3098.png)

Thanks again, 0.9.1 rolling out

**Comment by tulios** [comment]
@Wideshanks about the MAX_WAIT I agree with you, the intention was to be a number of times, the comment I added about the seconds was wrong, I reverted  to 20 attempts and I will change the name of this constant.
