### ISSUE TITLE
URL with IP instead of hostname not clickable

### ISSUE THREAD

**Issue by neketu** [tulios/json-viewer#40]
First, thank you for this great extension. One issue I'm running into:

http://192.1.1.254:8085/api -> non-clickable value

http://myhost.mydomain.com:8085/api -> clickable value

**Comment by tulios** [comment]
This happen probably because of regexp used [(url-pattern.js)](https://github.com/tulios/json-viewer/blob/master/extension/src/json-viewer/url-pattern.js), I will change it to include this case, Thanks.
