### ISSUE TITLE
Long numbers inside arrays

### ISSUE THREAD

**Issue by mariussoutier** [tulios/json-viewer#41]
Extension doesn't render long numbers correctly.

Try 39977290059340801. In an object, it will be displayed correctly. In an array, it gets rounded down to 39977290059340800.

**Comment by tulios** [comment]
Nice catch, I'll fix this asap. Thanks.

**Comment by tulios** [comment]
I used the solution proposed by @alexlopashev in another extension to wrap the numbers into a string to preserve the precision, I believe this issue now fixed for all scenarios.

**Comment by tulios** [comment]
Version 0.9.2 rolling out

**Comment by mariussoutier** [comment]
Looking good, thanks!
