### ISSUE TITLE
Handle JSONP returns that begin with a comment

### ISSUE THREAD

**Issue by benhollander** [tulios/json-viewer#50]
Many services, including Google, Facebook, and GitHub return JSONP that begins with a js comment in order to prevent attacks from Rosetta Flash ([reference](https://miki.it/blog/2014/7/8/abusing-jsonp-with-rosetta-flash/)).

Example URL:
https://graph.facebook.com/SOME_ID?method=get&pretty=0&sdk=joey&callback=FB.__globalCallbacks.f1c77f051c

Unfortunately, it looks like json-viewer doesn't detect that this type of return is JSONP, and therefore doesn't style it.

**Comment by tulios** [comment]
I saw this issue at night yesterday and you already fixed it :tada:
Thanks!
