### ISSUE TITLE
Unexpected token d when parsing one-liner containing "1(2d)"

### ISSUE THREAD

**Issue by itzg** [tulios/json-viewer#53]
Sorry for the ultra-specific issue title, but this is some kind of extreme edge case parsing error that I just happened to stumble upon with some of our application data. After narrowing down and scrubbing the content, I was able to recreate this error:

```
Error: contentExtractor: Unexpected token c
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1964
    at a (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3181)
    at p (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:4366)
    at new l (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3416)
    at r (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1735)
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:1408
    at o (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3131)
    at chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:3746
    at MutationObserver.r (chrome-extension://gbmdgpbipfallnflgajpaliibnhdgobh/assets/viewer.js:1:4761)
```

using this content:

```
{"a":[{"b":{"c":"1(2d)"}}]}
```

What's odd though, is if I re-format the JSON in IntelliJ, then json-viewer parses it fine. Here's the re-formatted content that works:

```
{
    "a": [
        {
            "b": {
                "c": "1(2d)"
            }
        }
    ]
}
```

**Comment by tulios** [comment]
Thanks @itzg for the debugging, I think that I know what is causing the problem. I will fix this today and release a bug fix version

**Comment by itzg** [comment]
Cool, thanks

**Comment by tulios** [comment]
@itzg what version of json-viewer you are using? Version 0.10.2 seems to be working

<img width="287" alt="screen shot 2015-08-12 at 19 29 13" src="https://cloud.githubusercontent.com/assets/33231/9231424/730547c2-4128-11e5-85b9-5f5d060e8f87.png">

json-viewer + TAB + {"a":[{"b":{"c":"1(2d)"}}]} + ENTER

**Comment by itzg** [comment]
0.10.2 is what I am using at the moment and like you I'm finding that it is working now. I didn't pay attention to the version that it was when submitting the bug...

**Comment by itzg** [comment]
...I also remembered I restarted my computer since then.

**Comment by tulios** [comment]
It happens, thanks for reporting! =D
