### ISSUE TITLE
What does it mean 'Inspect your json typing "json" in the console'?

### ISSUE THREAD

**Issue by jmjpro** [tulios/json-viewer#56]
How do we use this feature?

**Comment by tulios** [comment]
Hi @jmjpro, after loading your json if you open the inspector is possible to "play" with your json through the variable `json`. Check the image:

<img width="758" alt="screen shot 2015-08-26 at 08 34 48" src="https://cloud.githubusercontent.com/assets/33231/9486949/82d21518-4bcd-11e5-99ba-9490ca2d3a83.png">

**Comment by jmjpro** [comment]
Cool. I was trying to make it work in conjunction with the scratch pad feature. Does that already work?

**Comment by tulios** [comment]
Unfortunately no, scratch pad allows you to write anything and anything can be an invalid json. However, that's a good feature/idea I would like to have. If the json is valid I can create the variable.

**Comment by tulios** [comment]
Hey @jmjpro, there is any other dobts regarding the "inspect your JSON" feature? Can I close the issue?

**Comment by jmjpro** [comment]
Thanks @tulios Tullios. Closing it.
