### ISSUE TITLE
Not work on localhost

### ISSUE THREAD

**Issue by mazedulislamkhan** [tulios/json-viewer#57]
Hi,
It isn't wokring for me on my localhost development. I'm fetching a JSON result from a 3rd party site, however it's not highlighting the result. It works when it's not on localhost. I tried to enable it from the chrome -> extension options, however I've not find any relevant options on there which enable it for localhost. Is there anything I'm missing?

**Comment by tulios** [comment]
Hi @mazedulislamkhan, can you try to disable and re-enable the extension? Sometimes chrome mess up with the URL matches.

**Comment by mazedulislamkhan** [comment]
Hi,
I disabled and re-enabled it, no luck yet. Not sure why it's not working on localhost :/

**Comment by tulios** [comment]
:/ have you tried another project in localhost? And can you provide an example of the response? Maybe something in the response is crashing the plugin, have you noticed any error in the console?

**Comment by mazedulislamkhan** [comment]
Hi,
I've now tested with: https://api.github.com/repos/tulios/json-viewer this and it also didn't work. I've ran the result on the Chrome console and there's no error. On chrome console the JSON object is appearing correctly as expected.

Here's a sample result which I hope you find helpful:

{"sid":"SM3942f5f4e06d484ba6c6c567459fa107","date_created":"Thu, 27 Aug 2015 17:41:40 +0000","date_updated":"Thu, 27 Aug 2015 17:41:41 +0000","date_sent":"Thu, 27 Aug 2015 17:41:40 +0000","account_sid":"AC289516feb708fad78a83eec5d82b329d","to":"+16469267421","from":"+18554725915","body":"Thanks for the message. Configure your number's SMS URL to change this message.Reply HELP for help.Reply STOP to unsubscribe.Msg&Data rates may apply.","status":"delivered","num_segments":"1","num_media":"0","direction":"outbound-reply","api_version":"2010-04-01","price":"-0.00750","price_unit":"USD","error_code":null,"error_message":null,"uri":"\/2010-04-01\/Accounts\/AC289516feb708fad78a83eec5d82b329d\/Messages\/SM3942f5f4e06d484ba6c6c567459fa107","subresource_uris":{"media":"\/2010-04-01\/Accounts\/AC289516feb708fad78a83eec5d82b329d\/Messages\/SM3942f5f4e06d484ba6c6c567459fa107\/Media.json"}}

**Comment by tulios** [comment]
Thanks for the report. One last question, do you have any other json highlighter installed? And if it is the case, can you disable then and try again? Anyway I will test your data, thanks again!

**Comment by mazedulislamkhan** [comment]
Hi,
I was using a different syntax highlighter. However, it was one of them which I don't like at all. So I removed it today and then I installed yours.

If you find anything helpful for me then please do let me know :)

**Comment by tulios** [comment]
hey @mazedulislamkhan, I did some tests with your sample data and everything worked as expected. Can you try to reinstall the plugin? (uninstall/install)

localhost examples:
<img width="757" alt="working-example" src="https://cloud.githubusercontent.com/assets/33231/9643413/16761f22-51c2-11e5-98c0-99fd16ef499d.png">

**Comment by mazedulislamkhan** [comment]
Hi,
Not sure why it's not working on my end then :(

<img width="1392" alt="screen shot 2015-09-03 at 2 40 44 am" src="https://cloud.githubusercontent.com/assets/8946603/9643669/41caf8b4-51e5-11e5-9a51-d4781b86fbe1.png">

**Comment by tulios** [comment]
@mazedulislamkhan can you check the option `maxJsonSize` in the Add-Ons section, can you try to increase the value? I think that your json is bigger than the default max size.

**Comment by mazedulislamkhan** [comment]
Already tried that my friend :) no luck.

**Comment by tulios** [comment]
I really want to help with this problem :)

I'm suspecting that other plugin is changing the basic layout of chrome pages. Json-viewer will only activate in blank templates. Can you try in incognito mode with only json-viewer? And can you provide the page markup? (view page source of the json result page).

**Comment by mazedulislamkhan** [comment]
Hi,
Apologies for the excessive delay in responding. I've now tested it again using different environment with Laravel and it worked as expected. So previously there must be something that's preventing this. So the issue is now resolved then.

**Comment by tulios** [comment]
Ok, thanks for reporting.
