### ISSUE TITLE
Doesn't work at all, nothing happens when I open Json files in Chrome

### ISSUE THREAD

**Issue by invegat** [tulios/json-viewer#60]
![image](https://cloud.githubusercontent.com/assets/10525116/10020158/5a2e0c46-610f-11e5-8057-7df2cafe9eab.png)

**Comment by tulios** [comment]
Hi @invegat can you try to disable/enable the extension and try again.

**Comment by invegat** [comment]
I did before, but after I tried again and open/closed Chrome it worked!   Thanks!

**Comment by Coolerfall** [comment]
If the Content-Type is not application/json, it doesn't work yet.

**Comment by tulios** [comment]
The extension analyses the content to activate, it checks the chrome structure for raw content `body > pre`. It's not based in the Content-Type, I only can imagine that some another plugin has changed the default raw structure, it happened before with other users.

**Comment by FranciscoG** [comment]
when I view this JSON,  it does nothing:  
https://twitchemotes.com/api_cache/v2/subscriber.json

is it working for anyone else?  I have no other formatters installed

**Comment by tulios** [comment]
Hi @FranciscoG, I checked the URL you provided and it's not formatting due to the JSON size, you can change the option __maxJsonSize__ to 4000, for example. I will create an issue to alert about the size in the console.
<img width="915" alt="screen shot 2015-10-26 at 23 10 26" src="https://cloud.githubusercontent.com/assets/33231/10743993/f666d0ce-7c36-11e5-936b-88ae4cfb50ae.png">
<img width="549" alt="screen shot 2015-10-26 at 23 10 39" src="https://cloud.githubusercontent.com/assets/33231/10743995/fa427e32-7c36-11e5-9edc-d268394c32d8.png">

**Comment by FranciscoG** [comment]
@tulios thanks! i figured it might have been the maxSize.  I'll update my options.

**Comment by ryh95** [comment]
Can somebody tell me where to configure `maxJsonSize`  I can't find this option file 
Thanks!

**Comment by tulios** [comment]
Hi @ryh95, you have this config in the options page. You can go there in two ways: using the "gear" icon on your top right corner, or right clicking the extension and then clicking on "options"

![screen shot 2017-09-02 at 15 25 24](https://user-images.githubusercontent.com/33231/29995855-8a42cad8-8ff3-11e7-97d2-9730c854596b.png)
![screen shot 2017-09-02 at 15 25 38](https://user-images.githubusercontent.com/33231/29995854-8a4282d0-8ff3-11e7-8fa9-0b8f265d1777.png)
![screen shot 2017-09-02 at 15 25 46](https://user-images.githubusercontent.com/33231/29995856-8a431d1c-8ff3-11e7-8467-966856f1d188.png)

**Comment by Missypointyshoes** [comment]
For me, JSON viewer awesome was not working due to another Chrome Extension: ghostery. Once I disabled that, it worked fine.

**Comment by RushanKhan1** [comment]
@Missypointyshoes Wierd, same thing happened with me.

**Comment by evka85** [comment]
regular users follow this pattern: install plugin -> drop some json -> doesn't work -> uninstall. This is something that ought to work out of the box, just like opening a txt file with gedit..
after I repeated this with 3 different chrome extensions, I finally just opened firefox -> drop json (no extension needed) -> works

**Comment by AlanBlanchet** [comment]
For me I installed the extension and nothing worked apart from on the example websites.

![image](https://user-images.githubusercontent.com/22567306/143562683-848168c8-a874-420a-af03-87c428c9b4e4.png)

On local filesystem files it doesn't work for some reason.

I don't have any other extensions that would make it break.

**Comment by BenjaminBeck** [comment]
I do not have that "Options" option.
I tried the Firefox solution which showed me a error message: "SyntaxError: JSON.parse..."
After fixing it, this plugin worked.

-> Suggestion: If Content-Type is application/json - show an error if JSON is invalid.

**Comment by samvinko** [comment]
create another profile in your google chrome and check it again , the problem it coming from another extension make a conflict with json ,
