### ISSUE TITLE
CTRL+F to start default browser search functionallity

### ISSUE THREAD

**Issue by ivan-radic** [tulios/json-viewer#65]
Hi there, thanks for a great plugin.

Can you add an option to have shortcut CTRL+F start browser built-in functionality? Say CRTL+F for browser search, and CRTL+SHIFT+F for extension enhanced search dialog.

**Comment by tulios** [comment]
Hi @ivan-radic, there is an option to enable the browser search, can you check in the configurations page and see if it fits your needs?

Thanks!

**Comment by ivan-radic** [comment]
Thanks for a quick reply.

I did scan options page before coming here, but I did not see such option. I am using version 0.10.3. Do you mind pointing me where that option is? Thanks.

**Comment by ivan-radic** [comment]
Never mind. I found it, option is called ""alwaysRenderAllContent".

Thanks a lot, you can now close this issue as solved.

**Comment by tulios** [comment]
Thank you and sorry for the confuse option
