### ISSUE TITLE
Whitelist sites or check for JSON content

### ISSUE THREAD

**Issue by hanxue** [tulios/json-viewer#66]
Is it possible for JSON Viewer to whitelist only certain URLs to activate or alternatively check for valid JSON response before loading the CSS. 

The CSS loads on every page. This is slowing down web page loading as well as interfering in web development work.

**Comment by tulios** [comment]
Hi @hanxue, sorry for the delay (vacation time :)). Currently it checks the content. Maybe it's a bug, can you share the URL or is something internal? I'll perform a recheck to ensure that the code is correct. Thanks.
