### ISSUE TITLE
Doesn't work with files on the local filesystem

### ISSUE THREAD

**Issue by drocsid** [tulios/json-viewer#68]
I tried to open a local json file with file:///path/to/object.json . However the extension doesn't seem to parse it. I searched for a similar issue, but was suprised to not find one.

**Comment by tulios** [comment]
Hi @drocsid thanks for the issue, usually you have to give the extension permission for local files. Can you check issue #10 for more information, you didn't found any other issue related due to different titles.

Thanks!

**Comment by drocsid** [comment]
@tulios Thanks. Maybe put a mention of this on the README?
