### ISSUE TITLE
doesnt work with top level arrays

### ISSUE THREAD

**Issue by sandys** [tulios/json-viewer#69]
[test11.processed.json.gz](https://github.com/tulios/json-viewer/files/138996/test11.processed.json.gz)

works fine on www.jsoneditoronline.org

**Comment by tulios** [comment]
Thanks @sandys, it's probably a bug. I'll fix it.

**Comment by tulios** [comment]
Hi @sandys , it happens due to the JSON size. Can you check the option maxJsonSize, I increased mine  and it worked. I released a new version (0.11.0) warning about this in the console (issue #62).
Thanks!
