### ISSUE TITLE
Broken in Chrome 48.0.2564.116?

### ISSUE THREAD

**Issue by benhollander** [tulios/json-viewer#71]
It looks like this extension stopped working when Chrome moved all of the extension icons to the toolbar.
Or maybe I missed some step to re-enable it?

**Comment by tulios** [comment]
Hi @benhollander, I have the same version and it is working well, can you try to disable and enable the extension again? Do you have other JSON highlighter installed?

![screen shot 2016-03-10 at 08 59 47](https://cloud.githubusercontent.com/assets/33231/13662980/b563b93e-e69e-11e5-8d67-b06a32bd6587.png)

**Comment by benhollander** [comment]
It still doesn't work for me, but when I run it as the only extension enabled, it works.
There must be some other extension interfering (which seems likely, because a couple of other extensions I have don't seem to be working either).

I'll see if I can comb through and tell if there is some common global that should be avoided or something.

**Comment by tulios** [comment]
Hi @benhollander, do you have any news on this?

**Comment by benhollander** [comment]
I tried removing/reinstalling and it works now... weird. Not sure what happened.

**Comment by tulios** [comment]
Chrome probably crashed the background instance when it updated. I'll close the ticket now, thanks for the reporting!
