### ISSUE TITLE
doesnt work on umap responses

### ISSUE THREAD

**Issue by thoka** [tulios/json-viewer#73]
What do I have to do, to enable json-viewer on
http://umap.openstreetmap.fr/en/map/77793/geojson/

**Comment by tulios** [comment]
I need to investigate more but umap is returning content-type "text/html". I think this is forcing chrome to render the payload in a different way skipping the extension completely. Thanks for your report.

<img width="807" alt="screen shot 2016-03-29 at 23 45 29" src="https://cloud.githubusercontent.com/assets/33231/14124884/5ea17c84-f608-11e5-9e8e-22f13617b27c.png">

**Comment by tulios** [comment]
I copied the content to a file and it works well, it's probably the content type.

**Comment by tulios** [comment]
I don't think I have a fix to apply in this case, the response is "text/html" and I don't want the extension trying to find JSON against HTML responses. I found this code in the openstreepmap code I think I'll create a pull request for them changing to "application/json".
