### ISSUE TITLE
Add option to set the initial view mode

### ISSUE THREAD

**Issue by nnog** [tulios/json-viewer#76]
It would be nice to have an option to make it start "disabled" where the content is displayed raw, except for the 2 buttons on the right. Exactly as it looks when you click the raw button.
The reason this would be useful is because when you refresh it doesn't stay in the mode you last selected. Perhaps this could also be an additional optional feature too.

**Comment by tulios** [comment]
Hi @nnog, thats a super requested feature. I'll find some time this week to implement.
Thanks for reporting!
