### ISSUE TITLE
https://public.axdapi.com/d/match/035194c6-c683-40bc-9c5d-a801c577bca8

### ISSUE THREAD

**Issue by paetzy** [tulios/json-viewer#79]

**Comment by tulios** [comment]
Hi, what is the problem with this URL?

![screen shot 2016-04-21 at 11 06 15](https://cloud.githubusercontent.com/assets/33231/14703628/2009fca2-07b1-11e6-9a83-1a83b55ff89c.png)

Can you check the console logs, sometimes the content is bigger than the threshold configured at `maxJsonSize`. You can change this configuration in the options page.

**Comment by tulios** [comment]
I'll close this issue due to lack of information, feel free to reopen or comment in the future.

Thanks for the report.
