### ISSUE TITLE
Add Dracula Theme

### ISSUE THREAD

**Issue by heinst** [tulios/json-viewer#82]
Hi,

I see you dont have the dracula theme as an option and are using the css files on CodeMirror. There is a Dracula.css on there (https://codemirror.net/theme/dracula.css). Could you add this theme please?

**Comment by tulios** [comment]
Sure, I can add in the next release. It should be soon.
Thanks!

**Comment by tulios** [comment]
I have included a custom version of dracula as well. Nice suggestion!

Original:
<img width="358" alt="screen shot 2016-05-08 at 19 41 04" src="https://cloud.githubusercontent.com/assets/33231/15099959/65f9ccd0-1565-11e6-97de-549d565df8ef.png">

Custom:
<img width="389" alt="screen shot 2016-05-08 at 19 40 47" src="https://cloud.githubusercontent.com/assets/33231/15099960/65fdb886-1565-11e6-96cc-73b92aa50a87.png">

**Comment by tulios** [comment]
Released in version 0.13.0

**Comment by heinst** [comment]
Looks great! Thanks!
