### ISSUE TITLE
Extension works once?

### ISSUE THREAD

**Issue by tommygebru** [tulios/json-viewer#84]
Nevermind.... I believe it was just slow to load...

**Comment by tulios** [comment]
Hi @tommygebru, the extension has a feature which skips the highlight when the JSON payload is greater than a certain value, you can configure the value in the options page. Check the console to see if this is happening to you, I'll include a better interface to notify that, this is causing a lot of confusion.

**Comment by tommygebru** [comment]
hey! thanks... what is an appropriate amount? should I make it 4000?

**Comment by tulios** [comment]
It'll really depend on your case, I use 1024 (maybe I should make it the default value). I don't want to highlight huge JSON payloads but 1~4mb should be fine. I'll work to add some alert when the max value is reached.
