### ISSUE TITLE
json-viewer won't work for jsonp anymore after last commit

### ISSUE THREAD

**Issue by kylixd** [tulios/json-viewer#91]
I've noticed that since the last commit 3 days ago, not a single jsonp is getting formatted, not even the example from the main page: http://freemusicarchive.org/api/get/curators.jsonp?api_key=60BLHNQCAOUFPIBZ&callback=test

**Comment by tulios** [comment]
Oh, that's true. I've included a better check to avoid unecessary initialization but I missed JSONP. Thanks for the reporting.

**Comment by tulios** [comment]
Released on version 0.14.2. Thanks again!
